import Head from 'next/head';
import Image from 'next/image';
import CtaBtn from '../components/CtaBtn';

export default function Home() {
	return (
		<div>
			<Head>
				<title>Janskun Lanka</title>
				<meta name="description" content="Generated by create next app" />
			</Head>
			<div>
				<CtaBtn />
				<h1>slider</h1>
			</div>
		</div>
	);
}
