import Head from 'next/head';
import CtaBtn from '../components/CtaBtn';
import Slider from '../components/Slider';
import KumppanitSlider from '../components/KumppanitSlider';

export default function Home() {
	return (
		<div>
			<Head>
				<title>Janskun Lanka</title>
				<meta name="description" content="Generated by create next app" />
			</Head>
			<div>
				<Slider />
				<CtaBtn />
				<KumppanitSlider />
			</div>
		</div>
	);
}
